name: 'graph_density'

metric: 'manhattan' # ['euclidean', 'l2', 'l1', 'manhattan', 'cityblock',
                      # 'braycurtis', 'canberra', 'chebyshev', 'correlation',
                      # 'cosine', 'dice', 'hamming', 'jaccard', 'kulsinski',
                      # 'mahalanobis', 'matching', 'minkowski', 'rogerstanimoto',
                      # 'russellrao', 'seuclidean', 'sokalmichener',
                      # 'sokalsneath', 'sqeuclidean', 'yule', "wminkowski"]

