# ??? is a mandatory value.
# you should be able to set it without open_dict
# but if you try to read it before it's set an error will get thrown.

# populated at runtime
cwd: ???
seeds_count: 1

defaults:
  - model: encoder # [cnn, rnn, lm]
  - corpus: mimlre
  - strategy: random
  - embedding
  - preprocess
  - train
  - balance
  # - override hydra/output: custom




