# populated at runtime
vocab_size: ???
word_dim: 60
pos_size: ??? # 2 * pos_limit + 2
pos_dim: 50   # When it is sum, this value is invalid and is forcibly the same as word_dim

dim_strategy: 'cat' # [cat, sum]

