seed: 1

active_learning: False

total_iter: 50

use_gpu: True
gpu_id: 0

start_size : 2000 # Amount of labeled samples at the beginning
select_batch_size : 100
use_all_train : False
train_size : 10000 # Subset of training dataset to use

epoch: 6
batch_size: 64
learning_rate: 3e-4
lr_factor: 0.7 # Decay rate of learning rate
lr_patience: 3 # Waiting epoch with learning rate decay
weight_decay: 1e-3 # L2 regular

early_stopping_patience: 6

train_log: True
log_interval: 10
show_plot: True
only_comparison_plot: False
plot_utils: tensorboard  # [matplot, tensorboard]

predict_plot: True